-- begin ORDERMANAGEMENT_ADDRESS
alter table ORDERMANAGEMENT_ADDRESS add constraint FK_ORDERMANAGEMENT_ADDRESS_ON_CUSTOMER foreign key (CUSTOMER_ID) references ORDERMANAGEMENT_CUSTOMER(ID)^
create index IDX_ORDERMANAGEMENT_ADDRESS_ON_CUSTOMER on ORDERMANAGEMENT_ADDRESS (CUSTOMER_ID)^
-- end ORDERMANAGEMENT_ADDRESS
-- begin ORDERMANAGEMENT_LINE_ITEM
alter table ORDERMANAGEMENT_LINE_ITEM add constraint FK_ORDERMANAGEMENT_LINE_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references ORDERMANAGEMENT_PRODUCT(ID)^
alter table ORDERMANAGEMENT_LINE_ITEM add constraint FK_ORDERMANAGEMENT_LINE_ITEM_ON_ORDER foreign key (ORDER_ID) references ORDERMANAGEMENT_ORDER(ID)^
create index IDX_ORDERMANAGEMENT_LINE_ITEM_ON_PRODUCT on ORDERMANAGEMENT_LINE_ITEM (PRODUCT_ID)^
create index IDX_ORDERMANAGEMENT_LINE_ITEM_ON_ORDER on ORDERMANAGEMENT_LINE_ITEM (ORDER_ID)^
-- end ORDERMANAGEMENT_LINE_ITEM
-- begin ORDERMANAGEMENT_ORDER
alter table ORDERMANAGEMENT_ORDER add constraint FK_ORDERMANAGEMENT_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references ORDERMANAGEMENT_CUSTOMER(ID)^
create index IDX_ORDERMANAGEMENT_ORDER_ON_CUSTOMER on ORDERMANAGEMENT_ORDER (CUSTOMER_ID)^
-- end ORDERMANAGEMENT_ORDER
-- begin ORDERMANAGEMENT_DOCUMENT
alter table ORDERMANAGEMENT_DOCUMENT add constraint FK_ORDERMANAGEMENT_DOCUMENT_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table ORDERMANAGEMENT_DOCUMENT add constraint FK_ORDERMANAGEMENT_DOCUMENT_ON_ORDER foreign key (ORDER_ID) references ORDERMANAGEMENT_ORDER(ID)^
create index IDX_ORDERMANAGEMENT_DOCUMENT_ON_FILE on ORDERMANAGEMENT_DOCUMENT (FILE_ID)^
create index IDX_ORDERMANAGEMENT_DOCUMENT_ON_ORDER on ORDERMANAGEMENT_DOCUMENT (ORDER_ID)^
-- end ORDERMANAGEMENT_DOCUMENT
